ca_common_name = "bap.co cert"
ca_public_key_file_path = "ca.key.pem"
common_name = "bap.co cert"
organization_name = "bap"
owner = "ec2-user"
private_key_file_path = "vault.key.pem"
public_key_file_path = "vault.crt.pem"
validity_period_hours = "100"
ip_addresses = ["127.0.0.1"]
dns_names = ["vault.service.consul"]
